#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen bettynow' /etc/haproxy/haproxy.cfg
sed -i '/listen bettynow/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 16804-web-01 34.204.192.118:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 16804-web-01 34.204.192.118:80 check/a         server 16804-web-02 44.200.73.243:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start